In [28]:
import pandas as pd
df = pd.read_csv('../Dataset.csv')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [29]:
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [30]:
df.dropna(inplace=True)

In [31]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
le = LabelEncoder()
scaler = StandardScaler()

In [32]:
curr = le.fit_transform(df['Currency'])
curr

array([ 0,  0,  0, ..., 11, 11, 11])

In [33]:
names = le.fit_transform(df['Restaurant Name'])
vote = scaler.fit_transform(df[['Votes']])

In [34]:
dict_name = dict(zip(names, df['Restaurant Name']))

In [35]:
dict_name

{3742: 'Le Petit Souffle',
 3167: 'Izakaya Kikufuji',
 2892: 'Heat - Edsa Shangri-La',
 4700: 'Ooma',
 5515: 'Sambo Kojin',
 2068: 'Din Tai Fung',
 1006: 'Buffet 101',
 7170: 'Vikings',
 6037: 'Spiral - Sofitel Philippine Plaza Manila',
 3805: 'Locavore',
 5842: 'Silantro Fil-Mex',
 3901: "Mad Mark's Creamery & Good Eats",
 2755: "Guevarra's",
 5933: 'Sodam Korean Restaurant',
 1087: 'Cafe Arabelle',
 4598: "Nonna's Pasta & Pizzeria",
 615: 'Balay Dako',
 2932: 'Hobing Korean Dessert Cafe',
 7272: 'Wildflour Cafe + Bakery',
 4413: 'NIU by Vikings',
 6579: 'The Food Hall by Todd English',
 1471: 'Chez Michou',
 1206: 'Cafï¿½ï¿½ Daniel Briand',
 1294: 'Casa do Biscoito Mineiro',
 4022: 'Maori',
 4964: 'Pizza ï¿½ï¿½ Bessa',
 6162: 'Sushi Loko',
 705: 'Beirute',
 4512: 'New Koto',
 5530: 'Sandubas Cafï¿½ï¿½',
 7175: 'Villa Tevere',
 5391: 'Rovereto',
 1003: 'Buena Carne',
 6232: 'Taco Pep',
 1705: 'Coco Bambu',
 6335: 'Taypï¿½ï¿½',
 4731: 'Outback Steakhouse',
 4021: 'Manzuï¿½ï¿½',
 2605: 'Gero',
 947: 'Brazilian American Burgers',
 4893: 'Pesqueiro Eco Gourmet',
 1735: 'Confeitaria Colombo',
 777: 'Bibi',
 1308: 'Cervantes',
 301: 'Amir',
 6227: 'TT Burger',
 945: 'Braseiro da Gï¿½ï¿½vea',
 610: 'Balada Mix',
 2582: 'Garota de Ipanema',
 7399: 'Zazï¿½ï¿½ Bistrï¿½ï¿½ Tropical',
 2317: 'Filï¿½ï¿½ de Ouro',
 1836: 'D.O.C Ristorante',
 6161: 'Sushi Leblon',
 6257: 'Talho Capixaba',
 3753: 'Leme Light',
 5725: 'Shirley',
 5134: 'Quiosque Chopp Brahma',
 417: 'Aprazï¿½_vel',
 144: 'Aconchego Carioca',
 1269: 'Cantina Famiglia Mancini',
 6354: 'Templo da Carne - Marcos Bassi',
 2671: 'Gopala Hari',
 3250: 'Jiquitaia',
 5891: 'Skye - Hotel Unique',
 3760: 'Les 3 Brasseurs',
 5295: 'Red Steak & Burger',
 1270: 'Cantinho da Gula',
 4835: 'Paris 6 Classique',
 3435: 'Kawa Sushi',
 88: 'A Figueira Rubaiyat',
 3520: 'Kinoshita',
 4075: 'Meats',
 4833: 'Paribar',
 6362: 'Terraï¿½_o Itï¿½ï¿½lia',
 2080: 'Divino Fogï¿½ï¿½o',
 6141: 'Super Grill',
 2237: 'Esquina Mocotï¿½_',
 7153: 'Veloso',
 5490: 'Sainte Marie Gastronomia',
 501: "Austin's BBQ and Oyster Bar",
 520: "BJ's Country Buffet",
 2202: 'El Vaquero Mexican Restaurant',
 2207: 'Elements Coffee Co - Northwest',
 1490: 'Chick-fil-A',
 2754: 'Guang Zhou Chinese Restaurant',
 2867: 'Harvest Moon',
 2903: "Henry Campbell's Steakhouse",
 2946: 'Hong Kong Cafe',
 3018: 'House of China Restaurant II',
 3806: 'Locos Grill & Pub',
 3814: 'Longhorn Steakhouse',
 4144: 'Mikata Japanese Steakhouse',
 5745: 'Shogun Japanese Steak House',
 6485: 'The Catch Seafood Room & Oyster Bar',
 7173: 'Villa Gargano',
 39: '3 Squares Diner',
 7266: 'Whitebull Hotel',
 3703: 'Last Resort Grill',
 3983: "Mama's Boy Restaurant",
 6045: 'Sr. Sol 1',
 1641: 'Choo Choo Eastside',
 6618: 'The Grill',
 787: 'Big City Bread Cafe',
 1690: 'Clocked',
 1903: "DePalma's Italian Cafe - Downtown",
 1904: "DePalma's Italian Cafe - East Side",
 2341: 'Five & Ten',
 2738: 'Grit',
 3096: 'Ike & Jane',
 3646: 'La Dolce Vita Ristorante',
 5746: 'Shokitini',
 6302: 'Taqueria Del Sol',
 6719: 'The National',
 6779: 'The Royal Peasant',
 6964: 'Transmetropolitan',
 6965: 'Trappeze Pub',
 7195: 'Viva! Argentine Cuisine',
 4202: 'Miyabi Kyoto Japanese Steak House',
 5179: "Rae's Coastal Cafe",
 6418: "The Bee's Knees",
 912: 'Boll Weevil Cafe',
 2292: 'Farmhaus Burger',
 4019: "Manuel's Bread Cafe",
 5600: 'Sconyers Bar B Que',
 2505: 'Frog Hollow Tavern',
 2627: "Giuseppe's Pizza & Italian Specialities",
 4104: 'Mellow Mushroom',
 4419: 'Nacho Mamas Burritos',
 5319: "Rhinehart's Oyster Bar",
 6252: 'Takosushi',
 6515: 'The Chop House',
 6814: 'The Taj of India',
 491: 'Augsburg Haus',
 4898: 'Pho Bac',
 6373: 'Thai Kitchen',
 2197: 'El Kiosco Mexican Restaurant',
 6312: 'Taste of Balingup',
 966: 'Bridge Road Brewers',
 666: 'Bardenay',
 2352: 'Flatbread Neapolitan Pizzeria',
 2652: "Goldy's Breakfast Bistro",
 1354: 'Chandlers Steakhouse',
 658: 'Bar Gernika Basque Pub & Eatery',
 661: 'Barbacoa Restaurant',
 792: "Big Jud's",
 866: 'Bittercreek Ale House',
 911: 'Boise Fry Company',
 2379: 'Flying Pie Pizzaria',
 2462: 'Fork',
 2757: "Guido's Original New York Style Pizza",
 3828: "Los Beto's",
 3845: 'Lucianos Italian Restaurant',
 3948: 'Mai Thai Restaurant',
 5720: 'Shige Japanese Cuisine',
 6555: 'The Egg Factory',
 6987: 'Tucanos',
 6366: 'Texas Roadhouse',
 963: 'Brick 29',
 7276: 'Winifreds',
 776: "Biaggi's Ristorante Italiano",
 2200: 'El Super Burrito',
 2696: 'Granite City Food & Brewery',
 3157: 'Irish Democrat',
 6315: 'Taste of India',
 6374: 'Thai Moon Restaurant',
 6914: "Ting's Red Lantern",
 4257: "Monica's",
 2259: 'Exotic India',
 5749: 'Shorts Burger and Shine',
 6634: 'The Hamburg Inn No. 2 Inc.',
 895: 'Bluebird Diner',
 2702: 'Graze',
 85: "A & A Pagliai's Pizza",
 485: 'Atlas World Grill',
 875: 'BlackStone',
 2006: 'Devotay',
 3248: "Jimmy Jack's Rib Shack",
 7411: 'Zoeys Pizzeria',
 6940: 'Tokyo Sushi',
 731: 'Berry Patch Restaurant',
 5494: 'Sakura Sushi & Grill',
 7070: 'Uptown Vietnam cuisine',
 1143: 'Cafe Le Rue @ The Landings',
 4030: "Mark's City Grille",
 514: "B Merrell's",
 1266: 'Cannon Brewpub',
 2530: 'Fuji Japanese Steak House',
 5431: "Ruth Ann's Family Restaurant",
 5524: 'Samurai Japanese Cuisine & Sushi Bar',
 7235: 'Wasabi Sushi and Thai',
 999: 'Buckhead Bar and Grill',
 1046: "Burt's Butcher Shoppe and Eatery",
 1442: "Chef Lee's Peking Restaurant",
 1760: "Country's Barbecue",
 1971: "Deorio's",
 4111: 'Meritage',
 4255: 'Mongo The Mongolian Fire Pit',
 6439: 'The Black Cow',
 7288: 'Wood Stone',
 3062: "Hunter's Pub",
 1739: 'Consort Restaurant',
 6387: "Thatcher's Barbeque and Grill",
 1656: "Christian and Jake's Bistro",
 2129: "Dub's High on the Hog",
 5836: "Sierra's Mexican Restaurant",
 4640: 'Oakwood Cafe',
 1511: "Chili's Grill & Bar",
 2531: 'Fuji Japanese Steakhouse',
 3697: 'Las Palmas',
 6947: "Tony's Italian Restaurant & Pizza",
 2315: 'Filling Station',
 2344: 'Five Guys Burgers and Fries',
 3829: 'Los Pablos',
 3548: 'Kobe Hibachi & Sushi',
 5936: 'Soho Hibachi',
 6371: 'Thai Garden',
 5977: 'Southern Bliss Bakery',
 560: "Bailey's Bar-B-Que",
 2291: 'Farm To Fork',
 2941: 'Home Plate Grill',
 4908: 'Pie Slingers Pizzeria',
 4674: 'Olive Tree Cafe',
 5287: 'Red Ginger Sushi, Grill & Bar',
 1797: 'Crust Stone Oven Pizza',
 3249: "Jimmy's Pancake House",
 6967: 'Trattoria Tiramisu',
 5007: 'Prairie Grille at SteepleGate Inn',
 6296: 'Tantra Asian Bistro',
 2131: 'Duck City Bistro',
 2495: "Frick's Tap",
 3826: 'Los Agaves',
 511: 'Azteca',
 1542: 'China Cafe',
 2261: 'Exotic Thai Restaurant',
 2508: 'Front Street Brewery',
 3899: 'Machine Shed Restaurant',
 4724: 'Osaka',
 2907: 'Hickory Park',
 6467: 'The Cafe',
 2378: 'Flying Mango',
 1748: 'Cool Basil',
 3021: 'HuHot Mongolian Grill',
 3976: 'Malo',
 1307: 'Centro',
 2385: "Fong's Pizza",
 87: 'A Dong Restaurant',
 1761: 'Court Avenue Brewing Company',
 2085: 'Django',
 4201: 'Miyabi 9',
 7413: 'Zombie Burger + Drink Lab',
 7005: "Tursi's Latin King",
 6983: 'Tsing Tsao South',
 629: 'Bandit Burrito',
 3243: "Jethro's BBQ",
 6697: 'The Machine Shed Restaurant',
 4126: 'Mi Patria',
 7240: 'Waterfront Seafood Market',
 6600: 'The Giggling Goat',
 1045: 'Burnt Toast Cafe',
 1299: "Catfish Charlie's",
 5501: "Salsa's Mexican Restaurant",
 6945: "Tony Roma's",
 7182: "Vinny Vanucchi's",
 1349: 'Champps Americana',
 2311: 'Fiesta Cancun',
 2848: "Happy Joe's Pizza & Ice Cream",
 3013: "Houlihan's",
 3090: 'Ichiban Hibachi Steakhouse & Sushi Bar',
 3355: 'Kalmes Breaktime Bar & Grill',
 3637: 'L. May Eatery',
 3827: 'Los Aztecas',
 4012: 'Manna Java World Cafe',
 4029: "Mario's Italian Restaurant",
 4876: 'Pepper Sprout Incorporated',
 5750: 'Shot Tower Inn',
 6136: 'Sunshine Family Restaurant',
 7241: 'Watershed Cafe',
 7289: 'Woodfire Grille',
 6423: 'The Belle General',
 3239: 'Jehova es Mi Pastor Tacos y Burritos',
 2368: 'Flaxton Gardens',
 732: 'Bespoke Harvest',
 3014: 'Houndstooth Grill & Tavern',
 2881: 'Hawg Wild BBQ & Catfish House',
 940: 'Bourbon Street Grille',
 5911: 'Smokin Gold BBQ',
 2936: 'Hoka-Hoka Japanese Steak & Sushi',
 5708: "Shenanigan's Irish Pub",
 2334: 'Fish Tales Lakeside Grille',
 392: 'Antebellum',
 4272: "Moonie's Texas Barbecue",
 484: 'Atlanta Highway Seafood Market',
 2166: 'Eat at Thai',
 5903: 'Smoke House BBQ and Catering',
 24: '2 Dog',
 3817: 'Longstreet Cafe',
 5277: 'Re-Cess',
 908: 'Bodensee',
 2934: "Hofer's Bakery & Cafe",
 6976: 'Troll Tavern',
 6718: 'The Nacoochee Village Tavern & Pizzeria',
 885: 'Blue Bean Love Cafe',
 3656: 'La Trattoria of Lavandula',
 63: '5 Little Pigs',
 693: 'Beach Box Cafe',
 2537: 'Funkey Monkey',
 1030: 'Burger Queen Drive In',
 889: 'Blue Orchid Thai Restaurant',
 6079: 'Stillwater on Belmore',
 4313: 'Mr.',
 2219: "Emilio's Cuban Cafe",
 3140: 'Ingleside Village Pizza',
 3246: "Jim Shaw's Seafood Grill & Bar",
 4000: 'Mandarin Chinese Restaurant',
 5376: 'Rookery',
 927: 'Bonefish Grill',
 2114: 'Downtown Grill',
 2709: 'Greek Corner Deli',
 4447: "Natalia's",
 4813: "Papouli's Mediterranean Cafe & Market",
 726: "Benson's Steak and Sushi",
 4395: 'My Fathers Place',
 6164: 'Sushi Thai Restaurant',
 6706: 'The Mellow Mushroom',
 2196: 'El Jalisciense Mexican Restaurant',
 2711: 'Greek Village',
 4032: "Martin's BBQ",
 6377: 'Thai Pepper',
 7401: 'Zen Japanese Steakhouse and Sushi Bar',
 6069: 'Star Buffet',
 6971: 'Triangle Restaurant',
 6883: 'Three Anchors',
 7180: "Vince's Restaurant & Pizzeria",
 4982: 'Poets Cafe',
 6398: 'The Artesian Restaurant',
 1311: 'Cevï¿½_che Tapas Bar & Restaurant',
 6: "'Ohana",
 2154: 'Earl of Sandwich',
 5183: 'Raglan Road Irish Pub and Restaurant',
 1215: 'Cafï¿½ï¿½ Tu Tu Tango',
 6367: 'Texas de Brazil',
 559: 'Bahama Breeze Island Grille',
 3924: "Maggiano's Little Italy",
 2883: 'Hawkers Asian Street Fare',
 6251: 'Tako Cheena by Pom Pom',
 5611: 'Seasons 52 Fresh Grill',
 2937: "Hollerbach's Willow Tree Cafï¿½ï¿½",
 4987: "Pom Pom's Teahouse and Sandwicheria",
 7330: 'Yellow Dog Eats',
 6891: "Tibby's New Orleans Kitchen",
 6527: 'The Coop',
 937: 'Bosphorous Turkish Cuisine',
 2243: 'Ethos Vegan Kitchen',
 6764: 'The Ravenous Pig',
 7197: 'Vivo Bar and Grill',
 4910: 'Pier 70',
 2029: 'DiVine',
 1069: 'Cactus Flower Cafe Navarre',
 4071: "McGuire's Irish Pub & Brewery",
 4551: 'New Yorker Deli & Pizzeria',
 6986: 'Tu-Do Vietnamese Restaurant',
 1291: "Carrabba's Italian Grill",
 3187: "Jaco's Bayfront Bar and Grille",
 6833: 'The Tin Cow',
 1068: 'Cactus Flower Cafe',
 2022: 'Dharma Blue',
 2630: 'Global Grill',
 3089: 'Ichiban',
 6568: 'The Fish House',
 7008: 'Tuscan Oven',
 2375: 'Flounders Chowder House',
 2901: "Hemingway's Island Grill",
 4451: 'Native Cafe',
 4864: "Peg Leg Pete's",
 6610: 'The Grand Marlin',
 4721: 'Original Georgios Authentic Greek Food',
 2335: "Fisherman's Corner",
 3900: 'Mad Cowes Cafe',
 5427: 'Rupes Burgers',
 5336: 'Riverwalk Cafe',
 5402: 'Royal Hotel',
 1002: "Buddy's Italian Restaurant",
 1050: 'Butterburrs',
 1363: 'Chang Garden',
 2313: 'Fifth Street Bagelry',
 2662: "Goody's Deli",
 2707: 'Grecian Key Restaurant',
 4732: 'Outer Limits Fun Zone',
 4996: 'Portneuf Valley Brewing',
 5529: 'Sandpiper Restaurant & Lounge',
 5618: 'Senor Iguanas',
 6158: 'Sushi Family',
 6316: 'Taste of India Nepal',
 6375: 'Thai Paradise',
 6454: 'The Bridge',
 4607: 'Nosh Mahal',
 2195: 'El Herradero',
 673: 'Barrett Junction Cafe',
 890: 'Blue Point Grill',
 2623: "Giovanni's Shrimp Truck",
 3565: 'Kona Brewing Company',
 1710: 'Coconuts Fish Cafe',
 3505: 'Kihei Caffe',
 4259: 'Monkeypod Kitchen by Merriman',
 5552: 'Sansei Seafood Restaurant & Sushi Bar',
 6070: 'Star Noodle',
 271: 'Aloha Mixed Plate',
 2591: 'Gazebo',
 3028: 'Hula Grill',
 3506: "Kimo's",
 3986: "Mama's Fish House",
 4034: 'Marukame Udon',
 7323: 'Yard House',
 3854: "Lulu's Waikiki",
 2138: "Duke's Waikiki",
 2181: "Eggs 'n Things",
 5392: "Roy's",
 7223: 'Wailana Coffee House',
 6681: 'The Lady & Sons',
 2721: 'Green Truck Pub',
 3759: "Leopold's Ice Cream",
 4332: "Mrs. Wilkes' Dining Room",
 7420: "Zunzi's",
 4270: 'Moon River Brewing Company',
 4934: "Pirates' House Restaurant",
 517: "B. Matthew's Eatery",
 1799: 'Crystal Beer Parlor',
 2663: 'Goose Feathers Cafe and Bakery',
 2904: "Henry's",
 3027: "Huey's On The River",
 3171: "J. Christopher's",
 3853: "Lulu's Chocolate Bar",
 5351: 'Rocks on the River',
 5443: 'SOHO South Cafe',
 6733: 'The Olde Pink House',
 7158: "Vic's On The River",
 6530: 'The Crab Shack',
 5889: 'Sky On 57',
 1826: 'Cut By Wolfgang Puck',
 5311: 'Restaurant Andre',
 4998: 'Potato Head Folk',
 3183: 'Jaan',
 5320: 'Rhubarb Le Restaurant',
 233: "Al'frank Cookies",
 2473: 'Fratini La Trattoria',
 939: 'Boufe Boutique Cafe',
 6766: 'The Refinery Singapore',
 1668: 'Chye Seng Huat Hardware',
 3958: 'Makansutra Gluttons Bay',
 1724: 'Colony',
 6124: 'Summer Pavilion',
 6693: 'The Lokal',
 3079: 'I Am',
 6142: 'Super Loco',
 450: 'Artistry',
 867: 'Bitters & Love',
 449: 'Artichoke Cafe',
 430: "Archie's Waeside",
 899: "Bob Roe's Pizza",
 1846: 'Da Kao Restaurant',
 2287: "Famous Dave's",
 2528: 'Fuji Bay Japanese Restaurant',
 3030: 'Hunan Palace',
 3241: "Jerry's Pizza",
 3247: "Jim's Burgers",
 3256: 'Johnnie Mars',
 4151: 'Miles Inn',
 4159: 'Milwaukee Wiener House',
 4162: "Minerva's Food & Cocktails",
 4264: 'Monterrey Mexican Restaurant',
 5278: 'Rebos',
 6938: 'Tokyo Japanese Steakhouse & Sushi Bar',
 2034: 'Diamond Thai Cuisine',
 2194: 'El Fredo Pizza',
 6966: 'Trattoria Fresco',
 3333: "Kahill's Steak-Fish Chophouse",
 5419: 'Rumba Island Bar & Grill',
 5291: 'Red Mesa Cantina',
 712: 'BellaBrava',
 1309: 'Ceviche Tapas Bar & Restaurant',
 6713: 'The Moon Under Water',
 729: "Bern's Steak House",
 905: 'Boca Kitchen Bar Market',
 2176: 'Edison: Food+Drink Lab',
 1868: 'Daily Eats',
 5505: 'Salt Rock Grill',
 4068: "Mazzaro's Italian Market",
 1732: 'Conch Republic Grill',
 4323: "Mr. Dunderbak's Biergarten and Marketplatz",
 5292: 'Red Mesa Restaurant',
 1889: 'Datz',
 2213: "Ella's Americana Folk Art Cafe",
 6231: 'Taco Bus',
 6765: 'The Refinery',
 1727: 'Columbia Restaurant',
 19: '1918 Bistro & Grill',
 4911: 'Pig and Whistle',
 1005: 'Buffalo Wild Wings',
 2201: 'El Toreo Mexican Restaurant',
 41: '306 North Restaurant',
 502: 'Austins Cattle Co',
 702: 'Beijing Cafe',
 877: 'Bleu Cafe',
 878: 'Bleu Pub',
 997: 'Bubba Jax Crab Shack',
 1436: "Cheddar's Scratch Kitchen",
 2193: 'El Cazador',
 2500: 'Friends Grille and Bar',
 2626: 'Giulios Greek & Italian Restaurant',
 3648: 'La Jalisco Supermercato',
 4047: 'Masato Japanese',
 4236: "Mom & Dad's Italian Restaurant",
 4279: "Mori's Japanese Steakhouse & Sushi Bar",
 4841: 'Passage 2 India',
 5353: 'Rodeo Mexican Restaurant',
 6078: 'Steel Magnolias',
 5902: "Smok'n Pig B-B-Q",
 887: 'Blue House Cafe',
 343: 'Anchorage Cafe Restaurant Wine Bar',
 3681: 'Lake House Restaurant',
 4041: 'Masala Grill & Coffee House',
 988: 'Brown Bottle The Cedar Falls',
 2469: 'Four Queens Dairy Cream',
 2947: 'Hong Kong Chinese Restaurant',
 3170: "J's Homestyle Cooking",
 4263: 'Montage',
 4357: "Mulligan's Brick Oven Grill",
 5493: 'Sakura',
 5605: 'Scratch',
 5444: 'SOHO Sushi Bar & Deli',
 6948: "Tony's La Pizzeria",
 1372: 'Chapala',
 2560: 'Galleria de Paco',
 2646: 'Golden China',
 5418: "Rudy's Tacos",
 6786: 'The Screaming Eagle',
 6831: 'The Thai Bowl',
 6937: 'Tokyo Japanese Steak House',
 6875: "Theo Yianni's Authentic Greek Restaurant",
 2338: "Fishpatrick's Crabby Cafe",
 433: 'Arigato Sushi',
 1970: "Denny's",
 2288: "Famous Dave's Barbecue",
 4948: 'Pizza Di Rocco',
 5934: 'Sofra Istanbul',
 5502: 'Salt',
 2600: 'Genghis Grill',
 4672: 'Olive Garden',
 1605: 'Cho Gao - Crowne Plaza Abu Dhabi',
 5541: 'Sangeetha Vegetarian Restaurant',
 2985: 'Hot Palayok',
 415: "Applebee's",
 6902: 'Tikka Tonight',
 561: 'Bait El Khetyar',
 3113: 'Indian By Nature',
 7156: 'Via Delhi',
 5052: 'Punjab Grill',
 6260: 'Tamba',
 4745: "P.F. Chang's",
 6496: 'The Cheesecake Factory',
 6561: 'The Farm',
 3933: 'Maharaja Bhog',
 5265: 'Rasoi Ghar',
 663: 'Barbeque Nation',
 2294: 'Farzi Cafe',
 102: "AB's Absolute Barbecues",
 1288: 'Carnival By Tresind',
 2851: 'Hard Rock Cafe',
 6523: 'The Coffee Club',
 5435: 'SALT',
 6022: 'SpiceKlub',
 6970: 'Tresind - Nassima Royal Hotel',
 2685: 'Grand Barbeque Buffet Restaurant',
 5289: 'Red Lobster',
 4837: "Parker's",
 2751: 'Grub Shack',
 3368: 'Kamat',
 7108: 'Vadakkan Pepper',
 3426: 'Katis Restaurant',
 7394: 'Zaroob',
 1977: 'Derby',
 4471: 'Nayaab Haandi',
 4431: 'Najmat Lahore Restaurant',
 5462: 'Saffron',
 4953: 'Pizza Hut',
 225: 'Al Mukhtar Bakery',
 443: 'Aroos Damascus',
 4439: "Nando's",
 4866: 'Peking Chinese Restaurant',
 6224: "TGI Friday's",
 5206: 'Rajasthan Al Malaki',
 4811: 'Paper Fig',
 5881: 'Sis Burger',
 1764: 'Crafted Blends',
 3195: 'Jahanpanah',
 5253: 'Rangrezz Restaurant',
 6911: 'Time2Eat - Mama Chicken',
 1636: 'Chokho Jeeman Marwari Jain Bhojanalya',
 4914: 'Pinch Of Spice',
 4204: 'MoMo Cafe',
 4892: 'Peshawri - ITC Mughal',
 6238: 'Taj Bano - ITC Mughal',
 2545: 'G Thal',
 1894: 'Dawat-e-Nawab - Radisson Blu',
 6684: 'The Latitude - Radisson Blu',
 1887: 'Dasaprakash Restaurant',
 6493: 'The Charcoal Chimney',
 5718: 'Sheroes Hangout',
 922: 'Bon Barbecue',
 1373: 'Chapter 1 Cafe',
 4916: 'Pind Balluchi',
 6345: "Tea'se Me - Rooftop Tea Boutique",
 6370: 'Thaaliwala',
 72: '650 - The Global Kitchen',
 4851: 'Patang - The Revolving Restaurant',
 3023: 'Huber & Holly',
 84: '@Mango',
 2471: "Fozzie's Pizzaiolo",
 3651: "La Pino'z Pizza",
 4207: 'Mocha',
 884: 'Blue -  Rooftop Cafe Restaurant Bistro',
 4205: 'MoMo Cafï¿½ï¿½ - Courtyard By Marriott',
 1798: 'Cryo Lab',
 6191: 'Swati Snacks',
 964: 'Brick Kitchen',
 3324: 'Kabir Restaurant',
 5045: 'Puffizza',
 1082: 'Cafe Alfresco',
 6468: 'The Cafe Baraco',
 4578: "Nini's Kitchen",
 7322: 'Yanki Sizzlers',
 6595: 'The Garden Cafe - The Fern',
 4069: 'Mazzo',
 7004: 'Turquoise Villa',
 453: "Aryan Family's Delight",
 694: 'Bean Here',
 823: 'Bikanerwala',
 2008: 'Dewsis',
 2499: 'Friends Forever',
 3011: 'Hotel Ravisha Continental',
 3306: 'KFC',
 4070: "McDonald's",
 6098: 'Subway',
 6269: 'Tandoor Restaurant',
 6451: 'The BrewMaster',
 6815: 'The Tamarind Tree',
 1120: 'Cafe El Chico',
 2163: 'Eat On',
 2992: 'Hot Stuff',
 4818: 'Paradise',
 5470: 'Sagar Ratna',
 4294: 'Moti Mahal Delux',
 3961: 'Makhan Fish and Chicken Corner',
 1378: 'Charming Chicken',
 205: 'Ahuja Milk Bhandar',
 1800: 'Crystal Restaurant',
 971: 'Brijwasi Chat Bhandar',
 998: 'Bubby Fish & Chicken Corner',
 924: 'Bon Gateau',
 6863: 'The Yellow Chilli',
 3654: 'La Roma Pizzeria',
 5491: 'Sakhis Watz Kukin',
 6678: 'The Kulcha Land',
 5820: 'Shudh Restaurant',
 555: "Bade Bhai Ka Brothers' Dhaba",
 754: 'Bharawan Da Dhaba',
 985: 'Brothers Dhaba',
 986: "Brothers' Amritsari Dhaba",
 2791: 'Gurdas Ram Jalebi Wala',
 3464: 'Kesar Da Dhabha',
 698: 'Beera Chicken Corner',
 6153: 'Surjit Food Plaza',
 3378: 'Kanha Sweets',
 3578: 'Kream N Krunch',
 616: "Balbeer's Kitchen & Bar",
 353: 'Angeethi Restaurant',
 2096: "Domino's Pizza",
 3004: 'Hotel Laadli',
 3128: 'Indiana Veg Restaurant',
 3913: 'Madhuban Restaurant - Welcome Hotel Rama International',
 4060: 'Mauj Restaurant',
 4429: 'Naivedya',
 7424: "d' Curry House",
 4232: 'Mokoholic Juice Bar',
 465: "Ashoka's Veg Restaurant",
 3396: "Kareem's Fine Dining",
 6383: 'That Baat',
 767: 'Bhoj Restaurant',
 2112: 'Downside Up',
 3397: "Kareem's Kabab & Biryani",
 2705: 'Great Sagar Restaurant',
 3335: 'Kailash Restaurant',
 7320: 'Yalla Yalla',
 6121: 'Sultans of Spice',
 6564: 'The Fatty Bao - Asian Gastro Bar',
 6935: 'Toit',
 6884: 'Three Dots & A Dash',
 916: 'Bombay Brasserie',
 2628: "Glen's Bakehouse",
 4696: 'Onesta',
 2151: 'ECHOES Koramangala',
 6980: 'Truffles',
 6441: 'The Black Pearl',
 2164: 'Eat Street',
 3571: 'Koramangala Social',
 101: "AB's - Absolute Barbecues",
 2369: 'Flechazo',
 1730: 'Communiti',
 783: 'Big Brewsky',
 2953: 'Hoot',
 872: 'Black N White Cafe',

In [36]:
cuisines = le.fit_transform(df['Cuisines'])

In [37]:
cuisines_dummies = df['Cuisines'].str.get_dummies(sep=', ')
cuisines_dummies

,Afghani,African,American,Andhra,Arabian,Argentine,Armenian,Asian,Asian Fusion,Assamese,...,Teriyaki,Tex-Mex,Thai,Tibetan,Turkish,Turkish Pizza,Vegetarian,Vietnamese,Western,World Cuisine
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9549,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9550,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
cuisines_dummies.replace({0:False, 1:True}, inplace=True)

/tmp/ipykernel_2000/4001400465.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cuisines_dummies.replace({0:False, 1:True}, inplace=True)

In [39]:
df_with_dummies = pd.concat([df, cuisines_dummies], axis='columns')
df_without_dummies = df
df_without_dummies['Cuisines'] = cuisines

In [40]:
df_without_dummies

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,920,...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,1111,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,1671,...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,1126,...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,1122,...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,"Kemankeï¿½ï¿½ Karamustafa Paï¿½ï¿½a Mahallesi, RÛ±htÛ±m ...",Karakï¿½_y,"Karakï¿½_y, ï¿½ï¿½stanbul",28.977392,41.022793,1813,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,"Koï¿½ï¿½uyolu Mahallesi, Muhittin ï¿½ï¿½stï¿½_ndaï¿½ï¿½ Cadd...",Koï¿½ï¿½uyolu,"Koï¿½ï¿½uyolu, ï¿½ï¿½stanbul",29.041297,41.009847,1824,...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.034640,41.055817,1110,...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.036019,41.057979,1657,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,"Cafeaï¿½ï¿½a Mahallesi, BademaltÛ± Sokak, No 21/B, ...",Moda,"Moda, ï¿½ï¿½stanbul",29.026016,40.984776,331,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [41]:
df_with_dummies

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Teriyaki,Tex-Mex,Thai,Tibetan,Turkish,Turkish Pizza,Vegetarian,Vietnamese,Western,World Cuisine
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,False,False,False,False,False,False,False,False,False,False
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,False,False,False,False,False,False,False,False,False,False
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,False,False,False,False,False,False,False,False,False,False
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,False,False,False,False,False,False,False,False,False,False
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,"Kemankeï¿½ï¿½ Karamustafa Paï¿½ï¿½a Mahallesi, RÛ±htÛ±m ...",Karakï¿½_y,"Karakï¿½_y, ï¿½ï¿½stanbul",28.977392,41.022793,Turkish,...,False,False,False,False,True,False,False,False,False,False
9547,5908749,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,"Koï¿½ï¿½uyolu Mahallesi, Muhittin ï¿½ï¿½stï¿½_ndaï¿½ï¿½ Cadd...",Koï¿½ï¿½uyolu,"Koï¿½ï¿½uyolu, ï¿½ï¿½stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,False,False,False,False,False,False,False,False,False,True
9548,5915807,Huqqa,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.034640,41.055817,"Italian, World Cuisine",...,False,False,False,False,False,False,False,False,False,True
9549,5916112,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.036019,41.057979,Restaurant Cafe,...,False,False,False,False,False,False,False,False,False,False
9550,5927402,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,"Cafeaï¿½ï¿½a Mahallesi, BademaltÛ± Sokak, No 21/B, ...",Moda,"Moda, ï¿½ï¿½stanbul",29.026016,40.984776,Cafe,...,False,False,False,False,False,False,False,False,False,False

In [42]:
df_with_dummies['Restaurant Name'] = names
df_without_dummies['Restaurant Name'] = names

In [43]:
df_with_dummies.drop(columns=['Restaurant ID', 'City', 'Address', 'Locality', 'Locality Verbose', 'Latitude', 'Longitude', 'Rating color', 'Rating text', 'Cuisines', 'World Cuisine'], inplace=True)
df_without_dummies.drop(columns=['Restaurant ID', 'City', 'Address', 'Locality', 'Locality Verbose', 'Latitude', 'Longitude', 'Rating color', 'Rating text'], inplace=True)

In [44]:
df_with_dummies

,Restaurant Name,Country Code,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,...,Tea,Teriyaki,Tex-Mex,Thai,Tibetan,Turkish,Turkish Pizza,Vegetarian,Vietnamese,Western
0,3742,162,1100,Botswana Pula(P),Yes,No,No,No,3,4.8,...,False,False,False,False,False,False,False,False,False,False
1,3167,162,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,...,False,False,False,False,False,False,False,False,False,False
2,2892,162,4000,Botswana Pula(P),Yes,No,No,No,4,4.4,...,False,False,False,False,False,False,False,False,False,False
3,4700,162,1500,Botswana Pula(P),No,No,No,No,4,4.9,...,False,False,False,False,False,False,False,False,False,False
4,5515,162,1500,Botswana Pula(P),Yes,No,No,No,4,4.8,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,4436,208,80,Turkish Lira(TL),No,No,No,No,3,4.1,...,False,False,False,False,False,True,False,False,False,False
9547,1310,208,105,Turkish Lira(TL),No,No,No,No,3,4.2,...,False,False,False,False,False,False,False,False,False,False
9548,3063,208,170,Turkish Lira(TL),No,No,No,No,4,3.7,...,False,False,False,False,False,False,False,False,False,False
9549,512,208,120,Turkish Lira(TL),No,No,No,No,4,4.0,...,False,False,False,False,False,False,False,False,False,False
9550,7231,208,55,Turkish Lira(TL),No,No,No,No,2,4.0,...,False,False,False,False,False,False,False,False,False,False

In [45]:
df_without_dummies

,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes
0,3742,162,920,1100,Botswana Pula(P),Yes,No,No,No,3,4.8,314
1,3167,162,1111,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,591
2,2892,162,1671,4000,Botswana Pula(P),Yes,No,No,No,4,4.4,270
3,4700,162,1126,1500,Botswana Pula(P),No,No,No,No,4,4.9,365
4,5515,162,1122,1500,Botswana Pula(P),Yes,No,No,No,4,4.8,229
...,...,...,...,...,...,...,...,...,...,...,...,...
9546,4436,208,1813,80,Turkish Lira(TL),No,No,No,No,3,4.1,788
9547,1310,208,1824,105,Turkish Lira(TL),No,No,No,No,3,4.2,1034
9548,3063,208,1110,170,Turkish Lira(TL),No,No,No,No,4,3.7,661
9549,512,208,1657,120,Turkish Lira(TL),No,No,No,No,4,4.0,901
9550,7231,208,331,55,Turkish Lira(TL),No,No,No,No,2,4.0,591

In [46]:
df_with_dummies['Has Online delivery'].replace({'Yes':True, 'No':False}, inplace=True)
df_with_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
df_with_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
df_with_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)
df_without_dummies['Has Online delivery'].replace({'Yes':True, 'No':False},inplace=True)
df_without_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
df_without_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
df_without_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)

/tmp/ipykernel_2000/3953745716.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_with_dummies['Has Online delivery'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_with_dummies['Has Online delivery'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_with_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_with_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_with_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_with_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_with_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_with_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_without_dummies['Has Online delivery'].replace({'Yes':True, 'No':False},inplace=True)
/tmp/ipykernel_2000/3953745716.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_without_dummies['Has Online delivery'].replace({'Yes':True, 'No':False},inplace=True)
/tmp/ipykernel_2000/3953745716.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_without_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_without_dummies['Has Table booking'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_without_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_without_dummies['Is delivering now'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_without_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)
/tmp/ipykernel_2000/3953745716.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_without_dummies['Switch to order menu'].replace({'Yes':True, 'No':False}, inplace=True)

In [47]:
df_with_dummies.drop(columns='Currency', inplace=True)
df_without_dummies.drop(columns='Currency', inplace=True)

In [48]:
df

,Restaurant Name,Country Code,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes
0,3742,162,920,1100,True,False,False,False,3,4.8,314
1,3167,162,1111,1200,True,False,False,False,3,4.5,591
2,2892,162,1671,4000,True,False,False,False,4,4.4,270
3,4700,162,1126,1500,False,False,False,False,4,4.9,365
4,5515,162,1122,1500,True,False,False,False,4,4.8,229
...,...,...,...,...,...,...,...,...,...,...,...
9546,4436,208,1813,80,False,False,False,False,3,4.1,788
9547,1310,208,1824,105,False,False,False,False,3,4.2,1034
9548,3063,208,1110,170,False,False,False,False,4,3.7,661
9549,512,208,1657,120,False,False,False,False,4,4.0,901
9550,7231,208,331,55,False,False,False,False,2,4.0,591

In [49]:
df_with_dummies['Votes'] = vote
df_without_dummies['Votes'] = vote

In [50]:
X_dum = df_with_dummies.drop(columns='Restaurant Name')
y_dum = df_with_dummies['Restaurant Name']
X = df_without_dummies.drop(columns='Restaurant Name')
y = df_without_dummies['Restaurant Name']

In [51]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_dum, y_dum)
print(model.score(X_dum, y_dum))

model.fit(X, y)
print(model.score(X, y))

0.8751833997065604
0.8829385872982604

In [52]:
df_new = df_without_dummies
df_new['Currency'] = curr

In [53]:
X_new = df_new.drop(columns='Restaurant Name')
y_new = df_new['Restaurant Name']

In [54]:
model.fit(X_new, y_new)
model.score(X_new, y_new)

0.8829385872982604

In [55]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X, y)
model.score(X, y)

0.8885520734965074

In [58]:
y

0       3742
1       3167
2       2892
3       4700
4       5515
        ...
9546    4436
9547    1310
9548    3063
9549     512
9550    7231
Name: Restaurant Name, Length: 9542, dtype: int64

In [62]:
y_pred = [int(y) for y  in y_pred]

In [63]:
y_pred

[3742,
 3167,
 2892,
 4700,
 5515,
 2068,
 1006,
 7170,
 6037,
 3805,
 5842,
 3901,
 5842,
 2755,
 5933,
 1087,
 4598,
 615,
 2932,
 7272,
 4413,
 6579,
 1471,
 1206,
 1294,
 4022,
 4964,
 6162,
 705,
 4512,
 5530,
 7175,
 5391,
 1003,
 6232,
 1705,
 6335,
 4731,
 4021,
 1705,
 2605,
 947,
 4893,
 1735,
 777,
 1308,
 301,
 6227,
 945,
 610,
 2582,
 7399,
 2317,
 1836,
 6161,
 6257,
 3753,
 5725,
 5134,
 417,
 144,
 2582,
 1269,
 6354,
 2671,
 3250,
 5891,
 3760,
 5295,
 1270,
 4835,
 3435,
 88,
 3520,
 4075,
 4833,
 6362,
 2080,
 6141,
 2237,
 7153,
 5490,
 501,
 520,
 2202,
 2207,
 1490,
 2754,
 2867,
 2903,
 2946,
 3018,
 3806,
 3814,
 4144,
 5745,
 6485,
 7173,
 39,
 7266,
 3703,
 3983,
 6045,
 1641,
 6618,
 787,
 1690,
 1903,
 1904,
 2341,
 2738,
 3096,
 3646,
 5746,
 6302,
 6719,
 6779,
 6964,
 6965,
 7195,
 4202,
 5179,
 6418,
 912,
 2292,
 4019,
 5600,
 2505,
 2627,
 4104,
 4419,
 5319,
 6252,
 6515,
 6814,
 491,
 4898,
 5319,
 6373,
 2197,
 6312,
 966,
 666,
 2352,
 2652,
 1354,
 658,
 661,
 792,
 866,
 911,
 2379,
 2462,
 2757,
 3828,
 3845,
 3948,
 5720,
 6555,
 6987,
 6366,
 963,
 7276,
 776,
 2200,
 2696,
 3157,
 6315,
 6374,
 6914,
 4257,
 2259,
 5749,
 6634,
 895,
 2702,
 85,
 485,
 875,
 2006,
 3248,
 7411,
 6940,
 731,
 5494,
 7070,
 1143,
 4030,
 514,
 1266,
 2530,
 5431,
 5524,
 7235,
 999,
 1046,
 1442,
 1760,
 1971,
 4104,
 4111,
 4255,
 6439,
 7288,
 3062,
 1739,
 6387,
 1656,
 2129,
 5836,
 4640,
 1511,
 2531,
 3697,
 6947,
 2315,
 2344,
 3829,
 3548,
 5936,
 6371,
 5977,
 560,
 2291,
 2941,
 4908,
 4674,
 5287,
 1797,
 3249,
 6967,
 5007,
 6296,
 1490,
 2131,
 2495,
 3826,
 511,
 1542,
 2261,
 2508,
 2696,
 3826,
 3899,
 4724,
 6366,
 2907,
 6467,
 2378,
 1748,
 3021,
 3976,
 1307,
 2385,
 87,
 1761,
 2085,
 4201,
 7413,
 7005,
 6983,
 629,
 3243,
 6697,
 4126,
 7240,
 6600,
 1045,
 1299,
 5501,
 6945,
 7182,
 1349,
 2311,
 2848,
 3013,
 3090,
 3355,
 3637,
 3827,
 4012,
 4029,
 4876,
 5750,
 6136,
 7241,
 7289,
 6423,
 3239,
 2368,
 732,
 3014,
 2881,
 940,
 5911,
 2936,
 5708,
 2334,
 392,
 4272,
 484,
 2166,
 5903,
 24,
 3817,
 5277,
 908,
 2934,
 6976,
 6718,
 885,
 3656,
 63,
 693,
 2537,
 1030,
 889,
 6079,
 4313,
 2219,
 3140,
 3246,
 4000,
 5376,
 927,
 2114,
 2709,
 4447,
 4813,
 726,
 4395,
 6164,
 6706,
 2196,
 2711,
 4032,
 6377,
 7401,
 6069,
 6971,
 6883,
 7180,
 4982,
 6398,
 1311,
 6,
 2154,
 5183,
 1215,
 6367,
 559,
 3924,
 2883,
 6251,
 5611,
 2937,
 4987,
 7330,
 6891,
 6527,
 937,
 2243,
 6764,
 7197,
 4910,
 2029,
 1069,
 4071,
 4551,
 6986,
 1291,
 3187,
 6833,
 1068,
 2022,
 2630,
 3089,
 6568,
 7008,
 2375,
 2901,
 4451,
 4864,
 6610,
 4721,
 2335,
 3900,
 5427,
 6366,
 5336,
 5402,
 1002,
 1050,
 1363,
 2313,
 2662,
 2707,
 4732,
 4996,
 5529,
 5618,
 6158,
 6316,
 6375,
 6454,
 4607,
 2195,
 673,
 890,
 2623,
 3565,
 1710,
 3505,
 4259,
 5552,
 6070,
 271,
 2591,
 3028,
 3506,
 3986,
 4034,
 7323,
 3854,
 2138,
 2181,
 5392,
 7223,
 6681,
 2721,
 3759,
 4332,
 7420,
 4270,
 4934,
 517,
 1799,
 2663,
 2904,
 3027,
 3171,
 3853,
 5351,
 5443,
 6733,
 7158,
 6530,
 5889,
 1826,
 5311,
 4998,
 3183,
 5320,
 233,
 2473,
 939,
 6766,
 1668,
 3958,
 1724,
 6124,
 6693,
 3079,
 6142,
 450,
 867,
 449,
 430,
 899,
 1846,
 2287,
 2528,
 3021,
 3030,
 3241,
 3247,
 3256,
 4151,
 4159,
 4162,
 4264,
 5278,
 6938,
 2034,
 2194,
 6966,
 3333,
 5419,
 5291,
 712,
 1309,
 6713,
 729,
 905,
 2176,
 1309,
 1868,
 5505,
 4068,
 1732,
 4323,
 5292,
 1889,
 2213,
 6231,
 6765,
 1727,
 19,
 4911,
 1005,
 2201,
 41,
 502,
 702,
 877,
 878,
 997,
 1436,
 2193,
 2500,
 2626,
 3648,
 4047,
 4236,
 4279,
 4841,
 5353,
 6078,
 5902,
 887,
 343,
 3681,
 4041,
 988,
 2469,
 2947,
 3021,
 3170,
 4263,
 4357,
 5493,
 5605,
 5444,
 6366,
 6948,
 1372,
 2560,
 2646,
 5418,
 6786,
 6831,
 6937,
 6875,
 2338,
 433,
 1970,
 2288,
 4948,
 5934,
 5502,
 2600,
 4672,
 1605,
 2591,
 5541,
 2985,
 415,
 6902,
 561,
 3113,
 7156,
 5052,
 6260,
 4745,
 6496,
 6561,
 3933,
 5265,
 663,
 2294,
 102,
 1288,
 102,
 2851,
 6523,
 5435,
 2068,
 6022,
 6970,
 2685,
 5289,
 6496,
 4837,
 415,
 2751,
 3368,
 7108,
 2591,
 3426,
 7394,
 1977,
 4471,
 4431,
 5462,
 4953,
 225,
 443,
 4439,
 4866,
 6224,
 5206,
 415,
 4811,
 5881,
 1764,
 3195,
 5253,
 6911,
 1636,
 4914,
 4204,
 4892,
 6238,
 2545,
 1894,
 6684,
 1887,
 6493,
 5718,
 922,
 1373,
 4916,
 4953,
 6345,
 6370,
 72,
 4851,
 3023,
 84,
 2471,
 3651,
 4207,
 884,
 4205,
 1798,
 6191,
 964,
 3324,
 5045,
 1082,
 6468,
 4578,
 7322,
 6595,
 4069,
 7004,
 453,
 694,
 823,
 2008,
 2499,
 3011,
 3306,
 4070,
 4916,
 4953,
 6098,
 6269,
 6451,
 6815,
 1120,
 2163,
 2992,
 4818,
 5470,
 4294,
 3961,
 1378,
 205,
 1800,
 971,
 998,
 924,
 6863,
 3654,
 5491,
 6678,
 5820,
 555,
 754,
 985,
 986,
 2791,
 3464,
 698,
 6153,
 3378,
 3578,
 616,
 353,
 2096,
 3004,
 3128,
 3913,
 4060,
 4429,
 7424,
 4232,
 465,
 3396,
 6383,
 767,
 2112,
 3397,
 2705,
 3335,
 7320,
 6121,
 6564,
 6935,
 6884,
 916,
 2628,
 4696,
 4696,
 2151,
 6980,
 6441,
 2164,
 3571,
 101,
 2369,
 4696,
 1730,
 783,
 2953,
 2294,
 872,
 4065,
 5469,
 6666,
 576,
 7,
 1481,
 4953,
 3331,
 7186,
 654,
 1854,
 4807,
 576,
 4017,
 4017,
 3451,
 3115,
 6847,
 576,
 7018,
 5846,
 663,
 1306,
 6501,
 6310,
 4129,
 3990,
 83,
 151,
 1517,
 3686,
 5324,
 122,
 962,
 1330,
 3180,
 1314,
 2407,
 3950,
 2233,
 6723,
 983,
 1510,
 3629,
 4207,
 4933,
 663,
 6224,
 4777,
 4134,
 4566,
 4736,
 6140,
 6230,
 3399,
 7187,
 1039,
 7038,
 6384,
 2874,
 4803,
 4783,
 1510,
 7307,
 2538,
 1669,
 3334,
 916,
 4023,
 4818,
 3635,
 4783,
 4783,
 678,
 663,
 101,
 1702,
 4915,
 3593,
 2860,
 3536,
 7417,
 1024,
 6483,
 30,
 7123,
 835,
 6907,
 681,
 1179,
 1782,
 4693,
 6046,
 6386,
 1245,
 7324,
 1783,
 663,
 6760,
 6923,
 338,
 6960,
 3362,
 6613,
 522,
 5052,
 6220,
 7312,
 2173,
 2330,
 2141,
 2098,
 5275,
 663,
 874,
 1149,
 3210,
 3361,
 1994,
 3544,
 4516,
 5219,
 5226,
 4802,
 1357,
 4591,
 6955,
 6147,
 1086,
 2713,
 3558,
 3163,
 3818,
 4254,
 3796,
 4070,
 6157,
 728,
 2142,
 6513,
 1591,
 4743,
 6098,
 3306,
 663,
 7343,
 2617,
 4246,
 5778,
 4172,
 3994,
 2597,
 4589,
 349,
 6336,
 6769,
 451,
 5843,
 3909,
 3774,
 3861,
 3976,
 1252,
 1090,
 1144,
 3787,
 4246,
 4713,
 5465,
 5916,
 7248,
 2616,
 3150,
 4499,
 1532,
 1645,
 2968,
 5548,
 2509,
 4741,
 1680,
 3976,
 4084,
 214,
 398,
 1098,
 1484,
 1791,
 2509,
 2761,
 3032,
 3954,
 4246,
 4583,
 6632,
 7009,
 1156,
 977,
 1029,
 1131,
 1254,
 1401,
 1506,
 2616,
 2713,
 2869,
 3272,
 3472,
 3872,
 4881,
 4881,
 5626,
 6098,
 1204,
 462,
 680,
 1550,
 2827,
 3042,
 3382,
 4705,
 5279,
 6490,
 4254,
 4536,
 3090,
 3090,
 3516,
 3106,
 3976,
 4197,
 2162,
 3002,
 4246,
 4819,
 5285,
 5732,
 5935,
 6433,
 6930,
 6929,
 4836,
 5548,
 2853,
 3034,
 5762,
 6648,
 3163,
 820,
 1957,
 2381,
 4767,
 2748,
 3760,
 5110,
 6403,
 6147,
 2536,
 5722,
 3050,
 4254,
 3690,
 ...]